[2025-01-25T17:11:06.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T17:11:06.944+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-25T17:11:07.034+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-25T17:11:07.081+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T17:11:07.241+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-20 00:00:00+00:00
[2025-01-25T17:11:07.292+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4009) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-25T17:11:07.297+0000] {standard_task_runner.py:72} INFO - Started process 4029 to run task
[2025-01-25T17:11:07.313+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp46hz4iwe']
[2025-01-25T17:11:07.322+0000] {standard_task_runner.py:105} INFO - Job 499: Subtask create_table
[2025-01-25T17:11:08.680+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [running]> on host 50ab235b552a
[2025-01-25T17:11:09.452+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-01-25T17:11:09.458+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T17:11:09.464+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T17:11:09.492+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-25 17:11:06.959769+00:00
[2025-01-25T17:11:09.500+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-25T17:11:09.504+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T17:11:09.515+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-25T17:11:09.597+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-25T17:11:09.631+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-25T17:11:09.645+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 494, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 618, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 189, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-01-25T17:11:09.745+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T17:11:09.760+0000] {logging_mixin.py:190} INFO - Task start:2025-01-25 17:11:06.959769+00:00 end:2025-01-25 17:11:09.743947+00:00 duration:2.784178
[2025-01-25T17:11:09.762+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-20 00:00:00+00:00: scheduled__2025-01-20T00:00:00+00:00, state:running, queued_at: 2025-01-25 17:09:41.838467+00:00. externally triggered: False>
[2025-01-25T17:11:09.764+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2025-01-25T17:11:09.766+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250125T171106, end_date=20250125T171109
[2025-01-25T17:11:09.888+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T17:11:09.893+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 499 for task create_table (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 4029)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 494, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 618, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 189, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-01-25T17:11:10.016+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T17:11:10.797+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T17:11:10.809+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T06:41:19.990+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T06:41:20.098+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T06:41:20.132+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T06:41:20.134+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T06:41:20.560+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-20 00:00:00+00:00
[2025-01-26T06:41:20.580+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=681) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T06:41:20.585+0000] {standard_task_runner.py:72} INFO - Started process 711 to run task
[2025-01-26T06:41:20.588+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '598', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpt01mnfzi']
[2025-01-26T06:41:20.592+0000] {standard_task_runner.py:105} INFO - Job 598: Subtask create_table
[2025-01-26T06:41:20.745+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [running]> on host 34edd304782d
[2025-01-26T06:41:21.065+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-01-26T06:41:21.070+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T06:41:21.071+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T06:41:21.074+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 06:41:20.099956+00:00
[2025-01-26T06:41:21.075+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T06:41:21.077+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T06:41:21.079+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T06:41:21.106+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T06:41:21.129+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T06:41:21.277+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T06:41:21.288+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T06:41:21.360+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T06:41:21.363+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 06:41:20.099956+00:00 end:2025-01-26 06:41:21.358624+00:00 duration:1.258668
[2025-01-26T06:41:21.365+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-20 00:00:00+00:00: scheduled__2025-01-20T00:00:00+00:00, state:running, queued_at: 2025-01-26 06:40:12.050215+00:00. externally triggered: False>
[2025-01-26T06:41:21.367+0000] {logging_mixin.py:190} INFO - Failure caused by permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
[2025-01-26T06:41:21.369+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250126T064120, end_date=20250126T064121
[2025-01-26T06:41:21.473+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T06:41:21.476+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 598 for task create_table (permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
; 711)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T06:41:21.536+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T06:41:21.570+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T07:29:53.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T07:29:54.063+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T07:29:54.153+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T07:29:54.158+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T07:29:55.483+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-20 00:00:00+00:00
[2025-01-26T07:29:55.527+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1529) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T07:29:55.573+0000] {standard_task_runner.py:72} INFO - Started process 1555 to run task
[2025-01-26T07:29:55.552+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '679', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpl81snz1o']
[2025-01-26T07:29:55.587+0000] {standard_task_runner.py:105} INFO - Job 679: Subtask create_table
[2025-01-26T07:29:55.926+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [running]> on host 34edd304782d
[2025-01-26T07:29:56.833+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-01-26T07:29:56.844+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T07:29:56.853+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T07:29:56.857+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 07:29:54.064996+00:00
[2025-01-26T07:29:56.858+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T07:29:56.860+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T07:29:56.862+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T07:29:56.984+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T07:29:57.059+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T07:29:57.307+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T07:29:57.362+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T07:29:57.452+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T07:29:57.460+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 07:29:54.064996+00:00 end:2025-01-26 07:29:57.449900+00:00 duration:3.384904
[2025-01-26T07:29:57.480+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-20 00:00:00+00:00: scheduled__2025-01-20T00:00:00+00:00, state:running, queued_at: 2025-01-26 07:28:35.442991+00:00. externally triggered: False>
[2025-01-26T07:29:57.483+0000] {logging_mixin.py:190} INFO - Failure caused by permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
[2025-01-26T07:29:57.502+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250126T072954, end_date=20250126T072957
[2025-01-26T07:29:57.619+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T07:29:57.624+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 679 for task create_table (permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
; 1555)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T07:29:57.748+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T07:29:57.882+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T07:29:57.894+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T07:54:44.771+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T07:54:44.871+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T07:54:44.910+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T07:54:44.920+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T07:54:45.534+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-20 00:00:00+00:00
[2025-01-26T07:54:45.565+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T07:54:45.582+0000] {standard_task_runner.py:72} INFO - Started process 2230 to run task
[2025-01-26T07:54:45.597+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '774', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmprfivohq5']
[2025-01-26T07:54:45.610+0000] {standard_task_runner.py:105} INFO - Job 774: Subtask create_table
[2025-01-26T07:54:46.132+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [running]> on host 34edd304782d
[2025-01-26T07:54:47.140+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-01-26T07:54:47.176+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T07:54:47.181+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T07:54:47.183+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 07:54:44.873951+00:00
[2025-01-26T07:54:47.203+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T07:54:47.217+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T07:54:47.225+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T07:54:47.285+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T07:54:47.381+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T07:54:47.626+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T07:54:47.678+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T07:54:47.832+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T07:54:47.856+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 07:54:44.873951+00:00 end:2025-01-26 07:54:47.830419+00:00 duration:2.956468
[2025-01-26T07:54:47.866+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-20 00:00:00+00:00: scheduled__2025-01-20T00:00:00+00:00, state:running, queued_at: 2025-01-26 07:54:05.129093+00:00. externally triggered: False>
[2025-01-26T07:54:47.870+0000] {logging_mixin.py:190} INFO - Failure caused by permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
[2025-01-26T07:54:47.872+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250126T075444, end_date=20250126T075447
[2025-01-26T07:54:47.979+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T07:54:47.981+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 774 for task create_table (permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
; 2230)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T07:54:48.079+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T07:54:48.123+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T09:13:12.827+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T09:13:13.082+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T09:13:13.201+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T09:13:13.225+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T09:13:13.481+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-20 00:00:00+00:00
[2025-01-26T09:13:13.531+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3911) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T09:13:13.539+0000] {standard_task_runner.py:72} INFO - Started process 3942 to run task
[2025-01-26T09:13:13.597+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '998', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpvu_9eo0n']
[2025-01-26T09:13:13.655+0000] {standard_task_runner.py:105} INFO - Job 998: Subtask create_table
[2025-01-26T09:13:14.031+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [running]> on host 34edd304782d
[2025-01-26T09:13:14.809+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-01-26T09:13:14.833+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T09:13:14.837+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T09:13:14.844+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 09:13:13.086051+00:00
[2025-01-26T09:13:14.855+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T09:13:14.863+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T09:13:14.878+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T09:13:15.060+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T09:13:15.101+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T09:13:15.859+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T09:13:15.883+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T09:13:16.036+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T09:13:16.044+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 09:13:13.086051+00:00 end:2025-01-26 09:13:16.025638+00:00 duration:2.939587
[2025-01-26T09:13:16.061+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-20 00:00:00+00:00: scheduled__2025-01-20T00:00:00+00:00, state:running, queued_at: 2025-01-26 09:12:10.029525+00:00. externally triggered: False>
[2025-01-26T09:13:16.063+0000] {logging_mixin.py:190} INFO - Failure caused by permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
[2025-01-26T09:13:16.071+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250126T091313, end_date=20250126T091316
[2025-01-26T09:13:16.197+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T09:13:16.199+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 998 for task create_table (permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
; 3942)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T09:13:16.258+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T09:13:16.378+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T09:13:16.386+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T09:31:13.158+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T09:31:13.510+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T09:31:13.731+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-01-26T09:31:13.760+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T09:31:14.139+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-20 00:00:00+00:00
[2025-01-26T09:31:14.255+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4600) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T09:31:14.282+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '1114', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp3937odrg']
[2025-01-26T09:31:14.294+0000] {standard_task_runner.py:72} INFO - Started process 4623 to run task
[2025-01-26T09:31:14.325+0000] {standard_task_runner.py:105} INFO - Job 1114: Subtask create_table
[2025-01-26T09:31:14.989+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table scheduled__2025-01-20T00:00:00+00:00 [running]> on host 34edd304782d
[2025-01-26T09:31:16.299+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-01-26T09:31:16.376+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T09:31:16.400+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T09:31:16.404+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 09:31:13.586798+00:00
[2025-01-26T09:31:16.420+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T09:31:16.445+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T09:31:16.492+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS public.ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T09:31:16.698+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T09:31:16.867+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T09:31:17.191+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS public.ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T09:31:17.437+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T09:31:17.453+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250126T093113, end_date=20250126T093117
[2025-01-26T09:31:17.563+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-26T09:31:17.585+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-26T09:31:17.587+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks queued_at:2025-01-26 09:30:13.525736+00:00
[2025-01-26T09:31:17.588+0000] {logging_mixin.py:190} INFO - Task hostname:34edd304782d operator:PostgresOperator
[2025-01-26T09:31:17.753+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T09:31:18.151+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T09:31:18.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
