[2025-01-26T08:59:03.116+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T08:59:03.341+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T08:57:43.053872+00:00 [queued]>
[2025-01-26T08:59:03.499+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T08:57:43.053872+00:00 [queued]>
[2025-01-26T08:59:03.535+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T08:59:05.239+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-26 08:57:43.053872+00:00
[2025-01-26T08:59:05.389+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3444) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T08:59:05.416+0000] {standard_task_runner.py:72} INFO - Started process 3496 to run task
[2025-01-26T08:59:05.423+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'manual__2025-01-26T08:57:43.053872+00:00', '--job-id', '918', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpqjuhiyyr']
[2025-01-26T08:59:05.455+0000] {standard_task_runner.py:105} INFO - Job 918: Subtask create_table
[2025-01-26T08:59:05.925+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T08:57:43.053872+00:00 [running]> on host 34edd304782d
[2025-01-26T08:59:07.323+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T08:57:43.053872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T08:57:43.053872+00:00'
[2025-01-26T08:59:07.393+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T08:59:07.404+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T08:59:07.406+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 08:59:03.346426+00:00
[2025-01-26T08:59:07.408+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T08:59:07.412+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T08:59:07.534+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T08:59:07.810+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T08:59:07.856+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T08:59:08.384+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T08:59:08.485+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T08:59:08.717+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T08:59:08.727+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 08:59:03.346426+00:00 end:2025-01-26 08:59:08.714983+00:00 duration:5.368557
[2025-01-26T08:59:08.746+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-26 08:57:43.053872+00:00: manual__2025-01-26T08:57:43.053872+00:00, state:running, queued_at: 2025-01-26 08:57:43.148005+00:00. externally triggered: True>
[2025-01-26T08:59:08.761+0000] {logging_mixin.py:190} INFO - Failure caused by permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
[2025-01-26T08:59:08.771+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=manual__2025-01-26T08:57:43.053872+00:00, execution_date=20250126T085743, start_date=20250126T085903, end_date=20250126T085908
[2025-01-26T08:59:09.086+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T08:59:09.117+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 918 for task create_table (permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^
; 3496)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2:     CREATE TABLE IF NOT EXISTS ebooks (
                                       ^

[2025-01-26T08:59:09.490+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T08:59:09.737+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
