[2025-01-25T16:12:40.352+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T16:12:40.434+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.fetch_ebook_data scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-01-25T16:12:40.471+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.fetch_ebook_data scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-01-25T16:12:40.473+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-25T16:12:40.538+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_ebook_data> on 2025-01-13 00:00:00+00:00
[2025-01-25T16:12:40.562+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-25T16:12:40.571+0000] {standard_task_runner.py:72} INFO - Started process 3123 to run task
[2025-01-25T16:12:40.572+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'fetch_ebook_data', 'scheduled__2025-01-13T00:00:00+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp4zuwz75m']
[2025-01-25T16:12:40.576+0000] {standard_task_runner.py:105} INFO - Job 429: Subtask fetch_ebook_data
[2025-01-25T16:12:41.399+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.fetch_ebook_data scheduled__2025-01-13T00:00:00+00:00 [running]> on host 50ab235b552a
[2025-01-25T16:12:41.686+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='fetch_ebook_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T00:00:00+00:00'
[2025-01-25T16:12:41.690+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T16:12:41.692+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T16:12:41.694+0000] {logging_mixin.py:190} INFO - Current task name:fetch_ebook_data state:running start_date:2025-01-25 16:12:40.437346+00:00
[2025-01-25T16:12:41.697+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-25T16:12:41.700+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T16:12:49.985+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 42, in get_ebook_data
    df.drop_duplicates(subset="Title", inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6566, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6698, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['Title'], dtype='object')
[2025-01-25T16:12:50.043+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T16:12:50.045+0000] {logging_mixin.py:190} INFO - Task start:2025-01-25 16:12:40.437346+00:00 end:2025-01-25 16:12:50.041848+00:00 duration:9.604502
[2025-01-25T16:12:50.047+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_ebook_data> dag:<DAG: fetch_and_store_ebooks> dagrun:<DagRun fetch_and_store_ebooks @ 2025-01-13 00:00:00+00:00: scheduled__2025-01-13T00:00:00+00:00, state:running, queued_at: 2025-01-25 16:07:02.736940+00:00. externally triggered: False>
[2025-01-25T16:12:50.049+0000] {logging_mixin.py:190} INFO - Failure caused by Index(['Title'], dtype='object')
[2025-01-25T16:12:50.051+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=fetch_and_store_ebooks, task_id=fetch_ebook_data, run_id=scheduled__2025-01-13T00:00:00+00:00, execution_date=20250113T000000, start_date=20250125T161240, end_date=20250125T161250
[2025-01-25T16:12:50.106+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T16:12:50.108+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 429 for task fetch_ebook_data (Index(['Title'], dtype='object'); 3123)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 42, in get_ebook_data
    df.drop_duplicates(subset="Title", inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6566, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6698, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['Title'], dtype='object')
[2025-01-25T16:12:50.181+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T16:12:50.689+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-01-25T16:12:50.706+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T08:32:54.951+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T08:32:55.130+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.fetch_ebook_data scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-01-26T08:32:55.302+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.fetch_ebook_data scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-01-26T08:32:55.308+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2025-01-26T08:32:55.605+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_ebook_data> on 2025-01-13 00:00:00+00:00
[2025-01-26T08:32:55.714+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2669) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T08:32:55.752+0000] {standard_task_runner.py:72} INFO - Started process 2724 to run task
[2025-01-26T08:32:55.762+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'fetch_ebook_data', 'scheduled__2025-01-13T00:00:00+00:00', '--job-id', '800', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp8__pwl96']
[2025-01-26T08:32:55.775+0000] {standard_task_runner.py:105} INFO - Job 800: Subtask fetch_ebook_data
[2025-01-26T08:32:56.672+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.fetch_ebook_data scheduled__2025-01-13T00:00:00+00:00 [running]> on host 34edd304782d
[2025-01-26T08:32:59.069+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='fetch_ebook_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T00:00:00+00:00'
[2025-01-26T08:32:59.112+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T08:32:59.127+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T08:32:59.155+0000] {logging_mixin.py:190} INFO - Current task name:fetch_ebook_data state:running start_date:2025-01-26 08:32:55.138861+00:00
[2025-01-26T08:32:59.172+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T08:32:59.179+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T08:34:04.645+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T08:34:04.766+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T08:34:04.781+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_ebooks, task_id=fetch_ebook_data, run_id=scheduled__2025-01-13T00:00:00+00:00, execution_date=20250113T000000, start_date=20250126T083255, end_date=20250126T083404
[2025-01-26T08:34:04.971+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-26T08:34:04.978+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-26T08:34:04.986+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks queued_at:2025-01-26 08:32:12.136829+00:00
[2025-01-26T08:34:04.992+0000] {logging_mixin.py:190} INFO - Task hostname:34edd304782d operator:PythonOperator
[2025-01-26T08:34:05.105+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T08:34:05.224+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
